//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLBHEntities2 : DbContext
    {
        public QLBHEntities2()
            : base("name=QLBHEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<BillDetail> BillDetails { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<productAttr> productAttrs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int createAttr(Nullable<int> type, string value)
        {
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createAttr", typeParameter, valueParameter);
        }
    
        public virtual ObjectResult<getAttrByProductId_Result> getAttrByProductId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAttrByProductId_Result>("getAttrByProductId", idParameter);
        }
    
        public virtual ObjectResult<getProduct_Result> getProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getProduct_Result>("getProduct");
        }
    
        public virtual ObjectResult<getProductByCode_Result> getProductByCode(Nullable<int> code)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getProductByCode_Result>("getProductByCode", codeParameter);
        }
    
        public virtual ObjectResult<searchByCode_Result> searchByCode(Nullable<int> code)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<searchByCode_Result>("searchByCode", codeParameter);
        }
    
        public virtual ObjectResult<selectProduct_Result> selectProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectProduct_Result>("selectProduct");
        }
    
        public virtual ObjectResult<selectProductcate_Result> selectProductcate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectProductcate_Result>("selectProductcate");
        }
    
        public virtual ObjectResult<getBillDetailbyBill_Result> getBillDetailbyBill(Nullable<int> billId)
        {
            var billIdParameter = billId.HasValue ?
                new ObjectParameter("BillId", billId) :
                new ObjectParameter("BillId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getBillDetailbyBill_Result>("getBillDetailbyBill", billIdParameter);
        }
    
        public virtual ObjectResult<getBillDetailbyBill1_Result> getBillDetailbyBill1(Nullable<int> billId)
        {
            var billIdParameter = billId.HasValue ?
                new ObjectParameter("BillId", billId) :
                new ObjectParameter("BillId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getBillDetailbyBill1_Result>("getBillDetailbyBill1", billIdParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> getPrice(Nullable<int> code)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("getPrice", codeParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> getTotal(Nullable<int> code)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("getTotal", codeParameter);
        }
    
        public virtual ObjectResult<getPrice1_Result> getPrice1(Nullable<int> code)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPrice1_Result>("getPrice1", codeParameter);
        }
    
        public virtual ObjectResult<getInfoToEditBillDetail_Result> getInfoToEditBillDetail(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getInfoToEditBillDetail_Result>("getInfoToEditBillDetail", idParameter);
        }
    
        public virtual ObjectResult<GetInfoToEditBillDetail2_Result> GetInfoToEditBillDetail2(Nullable<int> idHoaDon)
        {
            var idHoaDonParameter = idHoaDon.HasValue ?
                new ObjectParameter("idHoaDon", idHoaDon) :
                new ObjectParameter("idHoaDon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoToEditBillDetail2_Result>("GetInfoToEditBillDetail2", idHoaDonParameter);
        }
    
        public virtual ObjectResult<getInfoToEditBillDetail1_Result> getInfoToEditBillDetail1(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getInfoToEditBillDetail1_Result>("getInfoToEditBillDetail1", idParameter);
        }
    
        public virtual ObjectResult<getInfoToEditBillDetail3_Result> getInfoToEditBillDetail3(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getInfoToEditBillDetail3_Result>("getInfoToEditBillDetail3", idParameter);
        }
    
        public virtual ObjectResult<getBillDetail_Result> getBillDetail(Nullable<int> billId)
        {
            var billIdParameter = billId.HasValue ?
                new ObjectParameter("BillId", billId) :
                new ObjectParameter("BillId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getBillDetail_Result>("getBillDetail", billIdParameter);
        }
    }
}
